packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests'

catalog:
  '@types/react': 18.3.28
  '@types/react-dom': 18.3.7
  classnames: 2.5.1
  lodash.debounce: 4.0.8
  merge-refs: 2.0.0
  react: 18.3.1
  react-dom: 18.3.1
  sass: 1.99.0
  typescript: 5.9.3
  uncontrollable: 9.0.0

ignoredBuiltDependencies:
  - ejs

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@cloud-ru/ft-config-husky'

saveWorkspaceProtocol: false

shamefullyHoist: true

sideEffectsCache: false
