packages:
  - packages/*
  - astro

ignoredBuiltDependencies:
  - ejs

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@cloud-ru/ft-config-husky'

saveWorkspaceProtocol: false

shamefullyHoist: true

sideEffectsCache: false
