export const TEST_IDS = {
  fieldDecorator: 'field-decorator',
  fieldDecoratorLabel: 'field-decorator__label',
  fieldDecoratorRequired: 'field-decorator__required-sign',
  fieldDecoratorLabelTooltip: 'field-decorator__label-tooltip',
  fieldDecoratorCaption: 'field-decorator__caption',
  fieldDecoratorHint: 'field-decorator__hint',
  fieldDecoratorCounter: 'field-decorator__counter',
  fieldCombo: 'field-combo',
  fieldComboInput: 'field-combo__input',
  fieldComboElementButton: 'field-combo__element-button',
  // Внутренняя оболочка (`fieldWrapper`): несёт effectiveValidationState (error форсит 'error'),
  // тогда как корень с публичным data-test-id хранит RAW `validationState`.
  fieldComboShell: 'field-combo__shell',
  fieldText: 'field-text',
  fieldTextInput: 'field-text__input',
  fieldTextShell: 'field-text__shell',
  // Кнопка копирования общая для всех полей (дефолт `useCopyButton`).
  fieldTextCopyButton: 'button-copy-value',
  fieldSecure: 'field-secure',
  fieldSecureInput: 'field-secure__input',
  fieldSecureHideButton: 'button-toggle-hidden',
  fieldSecureShell: 'field-secure__shell',
  // Skeleton, заменяющий input во время async-загрузки значения (asyncValueGetter).
  fieldSecureSkeleton: 'field-secure__skeleton',
  fieldTextArea: 'field-textarea',
  fieldTextAreaInput: 'field-textarea__input',
  fieldTextAreaScrollArea: 'field-textarea__scroll-area',
  fieldTextAreaShell: 'field-textarea__shell',
  fieldStepper: 'field-stepper',
  fieldStepperInput: 'field-stepper__input',
  fieldStepperMinus: 'field-stepper__minus-button',
  fieldStepperPlus: 'field-stepper__plus-button',
  fieldStepperCopyButton: 'field-stepper__copy-button',
  fieldStepperLimitTooltip: 'field-stepper__limit-tooltip',
  fieldSlider: 'field-slider',
  fieldSliderInput: 'field-slider__input',
  fieldSliderCopyButton: 'field-slider__copy-button',
  fieldSliderHandle: 'field-slider__slider',
  // Внутренняя оболочка слайдера: на ней живут data-validation-state / disabled / readonly /
  // withbackground / focusvisible (корень с data-test-id их не несёт).
  fieldSliderField: 'field-slider__field',
  fieldSelect: 'field-select',
  fieldSelectChips: 'field-select__chips',
  fieldSelectInput: 'field-select__input',
  fieldSelectClear: 'field-select__clear',
  fieldSelectCopy: 'field-select__copy',
  fieldDate: 'field-date',
  fieldDateInput: 'field-date__input',
  fieldDateInputFrom: 'field-date__input-from',
  fieldDateInputTo: 'field-date__input-to',
  fieldDateClear: 'field-date__clear',
  fieldDateCopy: 'field-date__copy',
  fieldDateCalendar: 'field-date__calendar',
  // CalendarDropdown (@ds/calendar) тегирует контент открытого календаря только когда ему передан
  // `data-test-id` (его билдер строит контент-узел как `content-<id>`). FieldDate проставляет этот id,
  // чтобы портальный календарь был адресуем в e2e/visual; реальный узел контента — `content-field-date__calendar-dropdown`.
  fieldDateCalendarDropdown: 'field-date__calendar-dropdown',
  fieldColor: 'field-color',
  fieldColorInput: 'field-color__input',
  fieldColorSwatch: 'field-color__swatch',
  fieldColorChevron: 'field-color__chevron',
  // ColorPicker (@ds/color-picker) тегирует свой корень только переданным data-test-id
  // (root рендерит `{...extractSupportProps(rest)}`). FieldColor проставляет этот id, чтобы
  // открытая палитра была адресуема в play/e2e.
  fieldColorPicker: 'field-color__picker',
  // Mobile: ColorPicker открывается в BottomSheet (адаптивный Dropdown); текущий цвет —
  // в title sheet'а, Cancel/Apply — в footer (Figma `colorPickerBottomSheet`).
  fieldColorSheetTitle: 'field-color__sheet-title',
  fieldColorCancel: 'field-color__cancel',
  fieldColorApply: 'field-color__apply',
  fieldTime: 'field-time',
  fieldTimeInput: 'field-time__input',
  fieldTimeIcon: 'field-time__icon',
} as const;
