import fs from 'fs';
import path from 'path';

import { parse, ParserOptions } from 'react-docgen-typescript';

import { logHelp, logInfo } from '../utils/console';
import { Markdown } from './Markdown';

const CAUTION = '[//]: THIS_SECTION_IS_AUTOGENERATED_PLEASE_DONT_EDIT_IT';
const CUSTOM_CONFIG = 'doc.config.ts';

type Options = {
  packagesRoot: string;
  docPlaceholder: [string, string];
  parserOptions: ParserOptions;
  targetFile?: 'README.md' | 'docs/index.mdx'; // Новый параметр для выбора целевого файла
};

export class Docgen {
  private readonly packagesRootPath: string;
  private readonly parserOptions: ParserOptions;
  private readonly docPlaceholder: [string, string];
  private readonly targetFile: string;

  constructor({
    packagesRoot,
    parserOptions,
    docPlaceholder,
    targetFile = 'docs/index.mdx',
  }: Options) {
    this.packagesRootPath = path.resolve(packagesRoot);
    this.parserOptions = parserOptions;
    this.docPlaceholder = docPlaceholder;
    this.targetFile = targetFile;
  }

  private path(...paths: string[]): string {
    return path.resolve(this.packagesRootPath, ...paths);
  }

  private readDocFile(packageName: string) {
    try {
      return fs.readFileSync(this.path(packageName, this.targetFile), 'utf-8');
    } catch (_e) {
      console.warn(`Error while reading ${this.targetFile} file in "${packageName}".`);
      return '';
    }
  }

  private getPackagesList() {
    const entities = fs.readdirSync(this.packagesRootPath);
    const packages = entities.filter((entity) => fs.statSync(this.path(entity)).isDirectory());
    const [startDocPlaceholder, endDocPlaceholder] = this.docPlaceholder;
    return packages.filter((packageName: string) => {
      const docFile = this.readDocFile(packageName);
      return docFile.includes(startDocPlaceholder) && docFile.includes(endDocPlaceholder);
    });
  }

  private writeDocsSectionToFile(packageName: string, doc: string) {
    const [placeholderStart, placeholderEnd] = this.docPlaceholder;
    const docFile = this.readDocFile(packageName);
    const startPosition = docFile.indexOf(placeholderStart);
    const endPosition = docFile.indexOf(placeholderEnd);

    const startOfFile = docFile.slice(0, startPosition);
    const endOfFile = docFile.slice(endPosition + placeholderEnd.length);

    fs.writeFileSync(
      this.path(packageName, this.targetFile),
      [
        startOfFile,
        [placeholderStart, CAUTION, doc, '\n', placeholderEnd].join('\n'),
        endOfFile,
      ].join(''),
      'utf-8'
    );
  }

  private async resolvePackageParserOptions(packageName: string): Promise<ParserOptions | null> {
    const optionsPath = path.resolve(this.packagesRootPath, packageName, CUSTOM_CONFIG);

    try {
      await fs.promises.access(optionsPath);

      logHelp(`ℹ load custom parserOptions for ${packageName}: ${packageName}/${CUSTOM_CONFIG}`);

      const { config } = await import(optionsPath);
      return config as ParserOptions;
    } catch (_e) {
      return null;
    }
  }

  private async generateDoc(packageName: string) {
    const packageSrc = path.resolve(this.packagesRootPath, packageName, 'src', 'index.ts');

    const packageDocOptions = await this.resolvePackageParserOptions(packageName);
    const parserOptions = packageDocOptions
      ? Object.assign(this.parserOptions, packageDocOptions)
      : this.parserOptions;

    return parse(packageSrc, parserOptions).map((docData) => {
      const doc = new Markdown(docData).renderPropsTable();
      logInfo(`✔ doc generated for ${packageName}/${this.targetFile} - ${docData.displayName}`);
      return doc;
    });
  }

  async run(packagesPaths: string[] = []) {
    const packages = this.getPackagesList();

    for (const packageName of packages) {
      if (
        packagesPaths.length &&
        !packagesPaths.some((packagePath) => packagePath.endsWith(packageName))
      ) {
        continue;
      }

      const docs = await this.generateDoc(packageName);
      this.writeDocsSectionToFile(packageName, docs.join('\n'));
    }
  }
}
