import fs from 'fs';
import path from 'path';

import { parse, ParserOptions } from 'react-docgen-typescript';

import { logHelp, logInfo, logWarning } from '../utils/console';
import { Markdown } from './Markdown';

const CAUTION = '[//]: THIS_SECTION_IS_AUTOGENERATED_PLEASE_DONT_EDIT_IT';
const CUSTOM_CONFIG = 'doc.config.ts';

type Options = {
  packagesRoot: string;
  docPlaceholder: [string, string];
  parserOptions: ParserOptions;
  targetFile?: 'README.md' | 'docs/index.mdx'; // Новый параметр для выбора целевого файла
};

export class Docgen {
  private readonly packagesRootPath: string;
  private readonly parserOptions: ParserOptions;
  private readonly docPlaceholder: [string, string];
  private readonly targetFile: string;

  constructor({ packagesRoot, parserOptions, docPlaceholder, targetFile = 'docs/index.mdx' }: Options) {
    this.packagesRootPath = path.resolve(packagesRoot);
    this.parserOptions = parserOptions;
    this.docPlaceholder = docPlaceholder;
    this.targetFile = targetFile;
  }

  private path(...paths: string[]): string {
    return path.resolve(this.packagesRootPath, ...paths);
  }

  private readDocFile(packageName: string, relativePath: string = this.targetFile) {
    try {
      return fs.readFileSync(this.path(packageName, relativePath), 'utf-8');
    } catch (_e) {
      return '';
    }
  }

  /** Рекурсивный список .mdx в docs/ (вложенность: components/Spinner.mdx, hooks/useX.mdx) */
  private getDocsMdxFilesRecursive(packageName: string): string[] {
    const docsDir = this.path(packageName, 'docs');
    if (!fs.existsSync(docsDir)) return [];
    const list: string[] = [];
    const walk = (dir: string, base = '') => {
      const items = fs.readdirSync(dir);
      for (const item of items) {
        const full = path.join(dir, item);
        const rel = base ? `${base}/${item}` : item;
        if (fs.statSync(full).isDirectory()) {
          walk(full, rel);
        } else if (item.endsWith('.mdx')) {
          list.push(rel);
        }
      }
    };
    walk(docsDir);
    return list.sort();
  }

  /** Пакет участвует в docgen, если хотя бы один файл в docs/ (в т.ч. вложенный) содержит оба плейсхолдера */
  private getPackagesList() {
    const entities = fs.readdirSync(this.packagesRootPath);
    const packages = entities.filter(entity => fs.statSync(this.path(entity)).isDirectory());
    const [startDocPlaceholder, endDocPlaceholder] = this.docPlaceholder;
    return packages.filter((packageName: string) => {
      const files = this.getDocsMdxFilesRecursive(packageName);
      return files.some(file => {
        const content = this.readDocFile(packageName, `docs/${file}`);
        return content.includes(startDocPlaceholder) && content.includes(endDocPlaceholder);
      });
    });
  }

  /** Записать секцию в конкретный файл (docs/index.mdx или docs/Counter.mdx) */
  private writeDocsSectionToFile(packageName: string, relativePath: string, doc: string) {
    const [placeholderStart, placeholderEnd] = this.docPlaceholder;
    const docFile = this.readDocFile(packageName, relativePath);
    const startPosition = docFile.indexOf(placeholderStart);
    const endPosition = docFile.indexOf(placeholderEnd);

    if (startPosition === -1 || endPosition === -1) {
      logWarning(`Placeholders not found in ${packageName}/${relativePath}, skip write`);
      return;
    }

    const startOfFile = docFile.slice(0, startPosition);
    const endOfFile = docFile.slice(endPosition + placeholderEnd.length);

    fs.writeFileSync(
      this.path(packageName, relativePath),
      [startOfFile, [placeholderStart, CAUTION, doc, '\n', placeholderEnd].join('\n'), endOfFile].join(''),
      'utf-8',
    );
  }

  private async resolvePackageParserOptions(packageName: string): Promise<ParserOptions | null> {
    const optionsPath = path.resolve(this.packagesRootPath, packageName, CUSTOM_CONFIG);

    try {
      await fs.promises.access(optionsPath);

      logHelp(`ℹ load custom parserOptions for ${packageName}: ${packageName}/${CUSTOM_CONFIG}`);

      const { config } = await import(optionsPath);
      return config as ParserOptions;
    } catch (_e) {
      return null;
    }
  }

  /**
   * Ключ для группировки: таблица без первой строки (### XProps), чтобы объединять одинаковые пропы.
   * TODO: обобщить — поддерживать пакеты с shared props через конфиг (doc.config.ts) или конвенцию.
   */
  private propsTableBodyKey(content: string): string {
    const firstLineEnd = content.indexOf('\n');
    return firstLineEnd === -1 ? content : content.slice(firstLineEnd + 1);
  }

  /**
   * FIXME: костыль под пакет icons — все иконки используют ISvgIconProps, в доке нужна одна таблица.
   * Результат: одна таблица ISvgIconProps для всех *SVG, одна SpriteProps для Sprite.
   */
  private deduplicateIconsProps(
    docs: Array<{ displayName: string; content: string }>,
  ): Array<{ displayName: string; content: string }> {
    const byBody = new Map<string, { displayNames: string[]; content: string }>();
    for (const { displayName, content } of docs) {
      const key = this.propsTableBodyKey(content);
      const existing = byBody.get(key);
      if (existing) {
        existing.displayNames.push(displayName);
      } else {
        byBody.set(key, { displayNames: [displayName], content });
      }
    }

    const result: Array<{ displayName: string; content: string }> = [];
    for (const { displayNames, content } of byBody.values()) {
      const isSpriteOnly = displayNames.length === 1 && displayNames[0] === 'Sprite';
      const isIconGroup = displayNames.some(name => name.endsWith('SVG'));
      const replaceHeader = isIconGroup && !isSpriteOnly;
      const newContent = replaceHeader ? content.replace(/^### \w+Props/, '### ISvgIconProps') : content;
      result.push({ displayName: displayNames[0], content: newContent });
    }
    result.sort((a, b) => {
      if (a.content.startsWith('### ISvgIconProps')) return -1;
      if (b.content.startsWith('### ISvgIconProps')) return 1;
      if (a.content.startsWith('### SpriteProps')) return -1;
      if (b.content.startsWith('### SpriteProps')) return 1;
      return 0;
    });
    return result;
  }

  private async generateDoc(packageName: string): Promise<Array<{ displayName: string; content: string }>> {
    const packageSrc = path.resolve(this.packagesRootPath, packageName, 'src', 'index.ts');
    if (!fs.existsSync(packageSrc)) return [];

    const packageDocOptions = await this.resolvePackageParserOptions(packageName);
    const parserOptions = packageDocOptions ? Object.assign(this.parserOptions, packageDocOptions) : this.parserOptions;

    let docs = parse(packageSrc, parserOptions).map(docData => ({
      displayName: docData.displayName,
      content: new Markdown(docData).renderPropsTable(),
    }));

    // FIXME: специальная логика только для icons (см. deduplicateIconsProps)
    if (packageName === 'icons' && docs.length > 0) {
      docs = this.deduplicateIconsProps(docs);
    }

    return docs;
  }

  async run(packagesPaths: string[] = []) {
    const packages = this.getPackagesList();
    const [placeholderStart, placeholderEnd] = this.docPlaceholder;

    for (const packageName of packages) {
      if (packagesPaths.length && !packagesPaths.some(packagePath => packagePath.endsWith(packageName))) {
        continue;
      }

      const docs = await this.generateDoc(packageName);
      const indexParts: string[] = [];

      const allMdx = this.getDocsMdxFilesRecursive(packageName);
      for (const { displayName, content } of docs) {
        const candidate = allMdx.find(f => f === `${displayName}.mdx` || f.endsWith(`/${displayName}.mdx`));
        const componentFile = candidate ? `docs/${candidate}` : `docs/${displayName}.mdx`;
        const componentPath = this.path(packageName, componentFile);
        if (fs.existsSync(componentPath)) {
          const fileContent = this.readDocFile(packageName, componentFile);
          if (fileContent.includes(placeholderStart) && fileContent.includes(placeholderEnd)) {
            this.writeDocsSectionToFile(packageName, componentFile, content);
            logInfo(`✔ doc generated for ${packageName}/${componentFile} - ${displayName}`);
            continue;
          }
        }
        indexParts.push(content);
      }

      const indexPath = this.path(packageName, this.targetFile);
      if (indexParts.length > 0 && fs.existsSync(indexPath)) {
        const indexContent = this.readDocFile(packageName, this.targetFile);
        if (indexContent.includes(placeholderStart) && indexContent.includes(placeholderEnd)) {
          this.writeDocsSectionToFile(packageName, this.targetFile, indexParts.join('\n'));
          logInfo(`✔ doc generated for ${packageName}/${this.targetFile} (${indexParts.length} component(s))`);
        }
      }
    }
  }
}
