export const FIGMA_TO_CSS_EXACT: Record<string, string | string[]> = {
  sizing: ['width', 'height'],
  'vertical-padding': ['padding-top', 'padding-bottom'],
  'horizontal-padding': ['padding-left', 'padding-right'],
  spacing: 'padding',
  'item-spacing': 'gap',
  dimension: 'gap',
  'corner-radius': 'border-radius',
  'corner-radius-left': ['border-top-left-radius', 'border-bottom-left-radius'],
  'corner-radius-right': ['border-top-right-radius', 'border-bottom-right-radius'],
  'corner-radius-top': ['border-top-left-radius', 'border-top-right-radius'],
  'corner-radius-bottom': ['border-bottom-left-radius', 'border-bottom-right-radius'],
  'corner-radius-top-left': 'border-top-left-radius',
  'corner-radius-top-right': 'border-top-right-radius',
  'corner-radius-bottom-left': 'border-bottom-left-radius',
  'corner-radius-bottom-right': 'border-bottom-right-radius',
  'border-radius-top-left': 'border-top-left-radius',
  'border-radius-top-right': 'border-top-right-radius',
  'border-radius-bottom-right': 'border-bottom-right-radius',
  'border-radius-bottom-left': 'border-bottom-left-radius',
  'stroke-weight': 'border-width',
  'stroke-weigth': 'border-width',
  'stroke-weight-horizontal': ['border-left-width', 'border-right-width'],
  'stroke-weight-vertical': ['border-top-width', 'border-bottom-width'],
  'stroke-weight-top': 'border-top-width',
  'stroke-weight-right': 'border-right-width',
  'stroke-weight-bottom': 'border-bottom-width',
  'stroke-weight-left': 'border-left-width',
  'stroke-weigth-horizontal': ['border-left-width', 'border-right-width'],
  'stroke-weigth-vertical': ['border-top-width', 'border-bottom-width'],
  'stroke-weigth-top': 'border-top-width',
  'stroke-weigth-right': 'border-right-width',
  'stroke-weigth-bottom': 'border-bottom-width',
  'stroke-weigth-left': 'border-left-width',
  'border-width': 'border-width',
  'border-width-top': 'border-top-width',
  'border-width-right': 'border-right-width',
  'border-width-bottom': 'border-bottom-width',
  'border-width-left': 'border-left-width',
  gap: 'gap',
  'content-gap': 'gap',
  'action-wrapper-gap': 'gap',
  'text-wrapper-gap': 'gap',
  padding: 'padding',
  'padding-left': 'padding-left',
  'padding-right': 'padding-right',
  'padding-top': 'padding-top',
  'padding-bottom': 'padding-bottom',
  'padding-horizontal': ['padding-left', 'padding-right'],
  'padding-vertical': ['padding-top', 'padding-bottom'],
  'content-padding': 'padding',
  'content-text-padding-vertical': ['padding-top', 'padding-bottom'],
  'content-text-padding-horizontal': ['padding-left', 'padding-right'],
  square: ['width', 'height'],
  width: 'width',
  height: 'height',
  'min-width': 'min-width',
  'max-width': 'max-width',
  'min-height': 'min-height',
  'max-height': 'max-height',
  'centered-wrapper-width': 'width',
  'centered-wrapper-height': 'height',
  'action-wrapper-height': 'height',
  'text-case': 'text-transform',
  'font-families': 'font-family',
  'font-weights': 'font-weight',
  'font-sizes': 'font-size',
  'line-height': 'line-height',
  'bg-default': 'background-color',
  'bg-hover': 'background-color',
  'bg-pressed': 'background-color',
  'bg-disabled': 'background-color',
  'fg-default': 'color',
  'fg-hover': 'color',
  'fg-pressed': 'color',
  'fg-disabled': 'color',
};

export const COMMON_CSS_PROP_NAMES = [
  'width',
  'height',
  'padding',
  'margin',
  'border',
  'border-radius',
  'border-width',
  'gap',
  'font-size',
  'font-weight',
  'font-family',
  'line-height',
  'color',
  'background',
  'background-color',
  'opacity',
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
] as const;
