export const dark = {
  'code[class*="language-"]': {
    background: 'hsl(220, 13%, 18%)',
    color: 'hsl(220, 14%, 71%)',
    textShadow: '0 1px rgba(0, 0, 0, 0.3)',
    fontFamily: '"Fira Code", "Fira Mono", Menlo, Consolas, "DejaVu Sans Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    background: 'hsl(220, 13%, 18%)',
    color: 'hsl(220, 14%, 71%)',
    textShadow: '0 1px rgba(0, 0, 0, 0.3)',
    fontFamily: '"Fira Code", "Fira Mono", Menlo, Consolas, "DejaVu Sans Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    overflow: 'auto',
    borderRadius: '0.3em',
  },
  'code[class*="language-"]::selection': {
    background: 'hsl(220, 13%, 28%)',
    color: 'inherit',
    textShadow: 'none',
  },
  'pre[class*="language-"] *::selection': {
    background: 'hsl(220, 13%, 28%)',
    color: 'inherit',
    textShadow: 'none',
  },
  ':not(pre) > code[class*="language-"]': {
    padding: '0.2em 0.3em',
    borderRadius: '0.3em',
    whiteSpace: 'normal',
  },
  comment: { color: 'hsl(220, 10%, 40%)', fontStyle: 'italic' },
  prolog: { color: 'hsl(220, 10%, 40%)' },
  punctuation: { color: 'hsl(220, 14%, 71%)' },
  'attr-name': { color: 'hsl(29, 54%, 61%)' },
  'class-name': { color: 'hsl(29, 54%, 61%)' },
  boolean: { color: 'hsl(29, 54%, 61%)' },
  constant: { color: 'hsl(29, 54%, 61%)' },
  number: { color: 'hsl(29, 54%, 61%)' },
  keyword: { color: 'hsl(286, 60%, 67%)' },
  property: { color: 'hsl(355, 65%, 65%)' },
  tag: { color: 'hsl(355, 65%, 65%)' },
  selector: { color: 'hsl(95, 38%, 62%)' },
  string: { color: 'hsl(95, 38%, 62%)' },
  builtin: { color: 'hsl(95, 38%, 62%)' },
  variable: { color: 'hsl(207, 82%, 66%)' },
  operator: { color: 'hsl(207, 82%, 66%)' },
  function: { color: 'hsl(207, 82%, 66%)' },
  url: { color: 'hsl(187, 47%, 55%)' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
