export const light = {
  'code[class*="language-"]': {
    background: 'hsl(230, 1%, 98%)',
    color: 'hsl(230, 8%, 24%)',
    fontFamily: '"Fira Code", "Fira Mono", Menlo, Consolas, "DejaVu Sans Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    background: 'hsl(230, 1%, 98%)',
    color: 'hsl(230, 8%, 24%)',
    fontFamily: '"Fira Code", "Fira Mono", Menlo, Consolas, "DejaVu Sans Mono", monospace',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    overflow: 'auto',
    borderRadius: '0.3em',
  },
  'code[class*="language-"]::selection': {
    background: 'hsl(230, 1%, 90%)',
    color: 'inherit',
  },
  'pre[class*="language-"] *::selection': {
    background: 'hsl(230, 1%, 90%)',
    color: 'inherit',
  },
  ':not(pre) > code[class*="language-"]': {
    padding: '0.2em 0.3em',
    borderRadius: '0.3em',
    whiteSpace: 'normal',
  },
  comment: { color: 'hsl(230, 4%, 64%)', fontStyle: 'italic' },
  prolog: { color: 'hsl(230, 4%, 64%)' },
  punctuation: { color: 'hsl(230, 8%, 24%)' },
  'attr-name': { color: 'hsl(35, 99%, 36%)' },
  'class-name': { color: 'hsl(35, 99%, 36%)' },
  boolean: { color: 'hsl(35, 99%, 36%)' },
  constant: { color: 'hsl(35, 99%, 36%)' },
  number: { color: 'hsl(35, 99%, 36%)' },
  keyword: { color: 'hsl(301, 63%, 40%)' },
  property: { color: 'hsl(5, 74%, 59%)' },
  tag: { color: 'hsl(5, 74%, 59%)' },
  selector: { color: 'hsl(119, 34%, 47%)' },
  string: { color: 'hsl(119, 34%, 47%)' },
  builtin: { color: 'hsl(119, 34%, 47%)' },
  variable: { color: 'hsl(221, 87%, 60%)' },
  operator: { color: 'hsl(221, 87%, 60%)' },
  function: { color: 'hsl(221, 87%, 60%)' },
  url: { color: 'hsl(198, 99%, 37%)' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
