export const TEST_IDS = {
  fieldMask: 'field-mask',
  fieldName: 'field-name',
  fieldDescription: 'field-description',
  fieldDescriptionAddButton: 'field-description__add-button',
  fieldPhone: 'field-phone',
  fieldPhoneCountrySelect: 'field-phone__country-select',
  fieldChat: 'field-chat',
  fieldCode: 'field-code',
  fieldCodeCell: 'field-code__cell',
  fieldCodeResend: 'field-code__resend',
  fieldChatUpload: 'field-chat__upload',
  fieldChatSubmit: 'field-chat__submit',
  fieldSelectCreate: 'field-select-create',
  fieldSelectCreateButton: 'field-select-create__button',
  fieldSelectCreateFooterButton: 'field-select-create__footer-button',
  fieldSelectCreateRetry: 'field-select-create__retry',
  fieldSelectCreateSurface: 'field-select-create__surface',
} as const;
