export const TEST_IDS = {
  main: 'toolbar',
  checkbox: 'toolbar__checkbox',
  confirmAction: 'toolbar__confirm-action',
  rejectAction: 'toolbar__reject-action',
  deleteAction: 'toolbar__delete-action',
  deactivateAction: 'toolbar__deactivate-action',
  disabledAction: 'toolbar__disabled-action',
  bulkTool: 'toolbar__bulk-tool',
  bulkActions: 'toolbar__bulk-actions',
  mobileBulkActionsSheet: 'toolbar__mobile-bulk-actions-sheet',
  moreBulkActionsButton: 'toolbar__more-bulk-actions-button',
  refreshButton: 'toolbar__refresh-button',
  refreshOption: 'toolbar__refresh-option',
  afterOption: 'toolbar__after-option',
  search: 'toolbar__search',
  filterButton: 'toolbar__filter-button',
  filterRow: 'toolbar__filter-row',
  moreActionsButton: 'toolbar__more-actions-button',
  droplist: 'toolbar__droplist',
  option: 'toolbar__droplist-option',
  after: 'toolbar__after',
  dataView: 'toolbar__data-view',
} as const;
